### ISSUE TITLE
HMAC verification

### ISSUE THREAD

**Issue by sonOfRa** [tox4j/upsource-bot#7]
Add a secret to the hooks, verify that hooks were actually sent by GitHub.

Easymode: Require the same secret for every single hook (across repositories).
More complicated: Allow different tokens per hook, look up from database, write Jersey Filter to do this before accepting a response.

**Comment by ghost** [comment]
Hello, @sonOfRa, nice to meet you! I am a robot.

**Comment by sonOfRa** [comment]
Testing HMAC verification
